### ISSUE TITLE
Need to add file handling for taking input

### ISSUE THREAD

**Issue by sg23600** [sandip2224/Rube_Goldberg_Machine#5]
A file input would make the project more user-friendly.

**Comment by sandip2224** [comment]
So @sg23600 you are handling the issue?

**Comment by sandip2224** [comment]
Remember every PR will need two approving reviews before being merged. 

So @ComputerScientist-01 and @sandip2224 (myself) will be reviewing the PR before merging. Sounds cool?

**Comment by ComputerScientist-01** [comment]
The updates have been added closing the issue

**Comment by sandip2224** [comment]
This issue has been resolved!!
